### ISSUE TITLE
Any way to change the vertex count?

### ISSUE THREAD

**Issue by andybak** [keenanwoodall/Deform-Prototype#3]
I'm still thinking about Deformers as if they were 3DS Max modifiers. I had an idea to create an array deformer but looking at the code it seems like you can't modify the vertex count - or the topology in general.

Before I spend any time on this, I wondered if this is even in scope for the project or if you've given it any thought?

**Comment by keenanwoodall** [comment]
That would definitely be cool to do. Right now the system isn't setup to support changing the vertex count or triangle indices, all it does is modify existing vertices. I'm afraid adding those controls will inhibit performance, but I won't rule it out for later.

**Comment by keenanwoodall** [comment]
I just added a delegate called `onDeformComplete`, which is invoked the moment the deformation calculations are finished. I also added the method `GetCurrentMesh` which returns the current mesh. Between the new delegate and method you could definitely create an array modifier (although it wouldn't be apart of the Deform system; it'd be your code stacked on top, just a temporary solution).
