### ISSUE TITLE
Animating curve of Taper Deformer

### ISSUE THREAD

**Issue by corbinyo** [keenanwoodall/Deform-Prototype#5]
Is this possible?

**Comment by keenanwoodall** [comment]
Animation curves aren't exposed to the animator, so no. What are you trying to do?

**Comment by corbinyo** [comment]
I would like to taper deform a mesh over time. Would there be another way of implementing this?

**Comment by keenanwoodall** [comment]
We'll as long as you are ok with using a linear curve , you can just make the animation curve a straight line at the height of one and animate the "top" and "bottom" floats.

**Comment by corbinyo** [comment]
Apologies, but I am not sure what you mean by this. This is something that would be done outside of the animator?

**Comment by keenanwoodall** [comment]
If you are ok with not using the curve to perform the taper, you can just use the "top" and "bottom" parameters which are animateable but can't do anything other than a linear taper.

Having a curve like this:
![image](https://user-images.githubusercontent.com/9631530/37732374-d1b8b528-2d12-11e8-8a9e-7b3849b7c267.png)

Is the same as setting top and bottom to this:
![image](https://user-images.githubusercontent.com/9631530/37732390-e1241192-2d12-11e8-84bc-45e35cfd0062.png)

If you don't see the top and bottom parameters in the inspector, make sure you have the newest version of deform (although be careful updating, this system is still in early development so big sweeping changes aren't uncommon)
