### ISSUE TITLE
MeshUtil breaks build

### ISSUE THREAD

**Issue by stalgiag** [keenanwoodall/Deform-Prototype#6]
The editor specific code in [MeshUtil](https://github.com/keenanwoodall/Deform/blob/master/Assets/Deform/Code/Utility/MeshUtil.cs#L1) is breaking the build process in 2017.4.0f1. Not sure what the best fix is for this yet. Depends on how that AssetDatabase asset is being used throughout the rest of the code.

**Comment by keenanwoodall** [comment]
Thanks for letting me know. I haven't updated Unity to 2017.4 yet. I'll look into that right now.

**Comment by keenanwoodall** [comment]
Where did you get 2017.4. I went on the website and only see 2017.3.1

**Comment by stalgiag** [comment]
I updated a few days ago. [It is available here.](https://unity3d.com/unity/whats-new/unity-2017.4.0) Is it able to build on older versions? I would assume even the namespace reference to UnityEditor would block builds on any version of unity. Definitely an `#if UNITY_EDITOR` check would work but not sure what the equivalent code outside the editor would be. Something related to the resources folder maybe?

**Comment by keenanwoodall** [comment]
Weird, when I click it it takes me to a page labeled 2017.3 
![2017 4 redirects to 2017 3](https://user-images.githubusercontent.com/9631530/38459057-98c4659a-3a6a-11e8-90ea-483048583a91.gif)

**Comment by keenanwoodall** [comment]
You are totally right about the UnityEditor thing tho, I'll fix that now.

**Comment by stalgiag** [comment]
Hehe not sure. It is possible that they didn't actually mean to make it an official release as 2018.1 is right around the corner. Somehow I ended up with it though!

![screenshot 70](https://user-images.githubusercontent.com/10382506/38459121-cf931c7a-3a5a-11e8-9872-82a1fc1067e6.png)

Thanks for working on the fix!

**Comment by keenanwoodall** [comment]
👍 Np. If you pull, you should be able to make builds now. Thanks for the feedback, I really appreciate it :)

**Comment by keenanwoodall** [comment]
I ended up moving the method that saves a mesh into an EditorMeshUtil class btw. Probably doesn't affect anything you are doing, but thats how I fixed the issue. Also I forgot to put the file in the editor folder so if you pulled quickly after I told you I fixed..I might not have fixed it. So pull again if you are still having problems lol

**Comment by stalgiag** [comment]
You are the best! Thank you so much!
