### ISSUE TITLE
Baking a mesh once edited in editor

### ISSUE THREAD

**Issue by yosun** [keenanwoodall/Deform-Prototype#9]
Can you include a feature to bake the mesh down if it is edited in Editor?

**Comment by keenanwoodall** [comment]
What do you mean by bake? Do you mean save the mesh to the project?

**Comment by keenanwoodall** [comment]
@yosun 

> Can you include a feature to bake the mesh down if it is edited in Editor?

What do you mean by bake? Do you mean save the mesh to the project?
